version: "4.20.0"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      JS_URL: http://localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springapp
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zmalqp.13
      - POSTGRES_DB=springapp
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
